Disable senseless GCC 7 warning about maybe-uninitialized fields
The GCC 7 output makes no sense because it doesn't explain where the
problem was. It only lists what fields were maybe uninitialized.

 In file included from qevdevgamepadbackend.cpp:37:0:
qevdevgamepadbackend_p.h: In member function ‘T& QHash<K, V>::operator[](const Key&) [with Key = int; T = QEvdevGamepadDevice::EvdevAxisInfo]’:
 qevdevgamepadbackend_p.h:82:12: error: ‘<anonymous>.QEvdevGamepadDevice::EvdevAxisInfo::flat’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     struct EvdevAxisInfo : public QGamepadBackend::AxisInfo<int>
            ^~~~~~~~~~~~~
 qevdevgamepadbackend_p.h:82:12: error: ‘<anonymous>.QEvdevGamepadDevice::EvdevAxisInfo::gamepadMinButton’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 qevdevgamepadbackend_p.h:82:12: error: ‘<anonymous>.QEvdevGamepadDevice::EvdevAxisInfo::gamepadMaxButton’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 qevdevgamepadbackend_p.h:82:12: error: ‘<anonymous>.QEvdevGamepadDevice::EvdevAxisInfo::gamepadLastButton’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

Change-Id: Ia3e896da908f42939148fffd14c4b1ac4a7f6943
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>